POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "de23@gmail.com",
    "password": "23"
}

### signin in 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "de23@gmail.com",
    "password": "23"
}

### find a user with id 
GET http://localhost:3000/auth/3


### find all users with emial 
GET http://localhost:3000/auth?email=ha@gmail.com


### delete a user with id 
DELETE  http://localhost:3000/auth/121

### update user

PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
    "password": "12"
}

### get loggedin user
GET http://localhost:3000/auth/whoami
### sign out loggedin user
POST http://localhost:3000/auth/signout

### set colors

GET http://localhost:3000/auth/colors/bluebre

###gget the colors 
GET http://localhost:3000/auth/colors



