POST  http://localhost:3000/reports
Content-Type: application/json

{
    "make":"audi",
    "model": "rs6",
    "year": 2021,
    "mileage": 2300,
    "lng": 45,
    "lat": 40,
    "price": 30
    
}

### singup user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "124@msn.se",
    "password": "12"

}

### signin

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "124@msn.se",
    "password": "12"

}

### signout

POST http://localhost:3000/auth/signout



###get na estimted for vechilce
GET  http://localhost:3000/reports?make=audi&model=rs6&lng=45&lat=45&mileage=10&year=2021




